"""Draft model changes

Revision ID: 6e98ea019f34
Revises: 5820629a8fca
Create Date: 2025-09-18 06:37:39.946258

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e98ea019f34'
down_revision: Union[str, Sequence[str], None] = '5820629a8fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('draft', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('drafts', 'article')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('article', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('drafts', 'draft')
    # ### end Alembic commands ###
