"""Comment db model update

Revision ID: 9207274da52d
Revises: 6e98ea019f34
Create Date: 2025-09-26 22:51:01.841134

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9207274da52d'
down_revision: Union[str, Sequence[str], None] = '6e98ea019f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('sentiment_analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('comments', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('comments', sa.Column('sentiment_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('comments', 'sentiment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('sentiment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'sentiment_keywords')
    op.drop_column('comments', 'sentiment_score')
    op.drop_column('comments', 'sentiment_analysis')
    # ### end Alembic commands ###
